######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 22 23:37:38 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += arrow.h bubble.h man.h \
    game.h
SOURCES += arrow.cpp bubble.cpp main.cpp man.cpp \
    game.cpp

OTHER_FILES += \
    images/arrow.png \
    images/archer_man.png \
    images/archer.png
